src/renderer/components/pages/HomePage.tsx
src/renderer/containers/ConnectedHomePage.ts
src/renderer/util/platform.ts
static/window/styles/styles.css

Link to the Trello request: https://trello.com/c/naQPHMmV
Visual screenshot:

Adding more stuff to the Home page - Trello

---

static/window/index.html
static/window/styles/core.css
static/window/styles/fancy.css

- Split CSS from one file into two different files (``core.css`` and ``fancy.css``)
* The first file (``core.css``) contains the styles that declare the size, position and such of elements
* The second file (``fancy.css``) contains the styles that improves the visuals of the elements (mostly changing the colors)
- Move values that are likely to be changed by custom themes into css variables of ``:root``
- Refactor some styles to be easier to override from custom themes (this still needs work and testing)

Clean up css

---

src/renderer/GameLauncher.ts

Environmental variables are case sensitive on Linux so Wine was ignoring them.

fix: Wine envars (case sensitive)

---

jest.config.js
tests/src/renderer/uuid.test.ts

What the title says - some basic Jest tests for `validateSemiUUID()`. The other export function probably needs to be mocked (the 'ole window object complaint). 
Let me know if I missed an edge case to test.

Adding basic tests for src/renderer/uuid.ts

---

lang/en.json
lang/pt.json
src/renderer/GameLauncher.ts
src/renderer/LaunchboxData.tsx
src/renderer/app.tsx
src/renderer/curate/parse.ts
src/renderer/game/GameManager.ts
src/renderer/util/lang.ts
src/shared/Util.ts
src/shared/lang/types.ts

**fix: Open File Location fallback for missing platforms** - https://trello.com/c/xuhF1ygo
**feat: Notes alias for animations (meta)** - https://discordapp.com/channels/432708847304704010/496132309498724391/620819857314676736
**fix: Improvements to Platform XML parsing and Footer counter** - https://trello.com/c/mVgie98Q and https://trello.com/c/AyRLaSHv
Changes platform XML parsing to only parse files ending in .xml. If it fails to parse a file, it stores the error and rejects them all in an array after the rest have finished parsing. These are printed to the log and the user is warned that *N* platform xmls have failed to parse, and to check the log for details.
Failed XML parsing no longer sets gamesFailedLoading (only set if the platforms path is missing entirely, aka Flashpoint path …

Various fixes and improvements

---

lang/en.json
src/renderer/components/GameOrder.tsx
src/renderer/util/lang.ts
src/shared/game/GameFilter.ts
src/shared/lang/types.ts
src/shared/order/interfaces.ts
src/shared/order/util.ts

https://trello.com/c/VIedDh0p
Should use `has:developer` and `has:publisher` filters from reworked search system if you don't wish to see empty developer/publisher entries.

feat: Developer and Publisher order opts

---

src/back/index.ts

This fix allows FP to appropriately read the `execs.json` file from `root/Data` (given `root` is the Flashpoint directory, selected by the user at upgrading time), and not from `root` itself.
Thanks to @colin969 for the suggestion!

Fix execs.json lookup path. (Suggestion by Colin)

---

src/back/GameLauncher.ts
src/back/ServicesFile.ts
src/main/Flash.ts
static/window/flash_index.html

To address the first bullet under https://bluemaxima.org/flashpoint/datahub/Mac_Support#Launcher_Issues
The change in GameLauncher is to have the `execMappings` applied to the `applicationPath` before the switch statement, else the override that I have in execs.json for `:flash:` does not work.

Mac: Prevent error logs when parsing services.json

---

src/renderer/components/pages/ConfigPage.tsx
src/renderer/components/pages/DeveloperPage.tsx
static/window/styles/core.css

Disable selection of most elements in the renderer.
The exceptions are the obvious input elements and some selected text elements (such as the ID of playlists).
Being able to select almost any text seems mostly pointless (except for when translating?) and makes the application feel cheaper imo.

feat: disable selection of most text in the renderer

---

src/renderer/Util.ts
src/renderer/app.tsx
src/renderer/components/Footer.tsx
src/renderer/components/GameGrid.tsx
src/renderer/components/GameList.tsx
src/renderer/components/Header.tsx
src/renderer/components/RandomGames.tsx
src/renderer/components/pages/BrowsePage.tsx
src/renderer/components/pages/TagCategoriesPage.tsx
src/renderer/components/pages/TagsPage.tsx
src/renderer/containers/ConnectedApp.ts
src/renderer/containers/ConnectedFooter.ts
src/renderer/containers/withMainState.ts
src/renderer/index.tsx
src/renderer/router.tsx
src/renderer/store/index.ts
src/renderer/store/main/enums.ts
src/renderer/store/main/reducer.ts
src/renderer/store/main/types.ts

The state of the App component is now kept in a Redux store instead (the store is called "main").
Views now keep a unique ID for the most recent query. This allows it to ignore outdated actions and eliminate some race conditions.
Adding games to the random games queue no longer discards a portion of the queued games.
Some minor cleanup has been made (remove some redundant state, remove some props passed down from main etc.)

refactor: Move app state to redux store

---

src/back/ManagedChildProcess.ts

`stdout` and `stderr` are regular streams that do not buffer lines, so we cannot guarantee that the buffer received from the `data` event ends in a new line, resulting in lines being cut-off when logging them, as this appends a new line at the end.

fix: Avoid cutting lines when printing output from child processes

---

lang/en.json
src/renderer/components/pages/CuratePage.tsx
src/renderer/curate/importCuration.ts
src/shared/lang.ts
src/shared/preferences/interfaces.ts
src/shared/preferences/util.ts

Currently, the launcher will assign a new UUID to every imported curation archive, this is potentially unwanted behavior, as it doesn't allow of proper tracking of games outside of the launcher. This change adds a checkbox to the curation page that allows reuse of UUIDs from said archives whenever possible, this would be enabled by default.

feat: Add keep archive key option to curate page

---

src/back/GameLauncher.ts

Fixes #159.
As explained in #159, launching certain games currently fails on Linux because single quotes (apostrophes) are not escaped; however, some games also use single quote pairs that should not be escaped. Searching through the current catalog, there are 542 titles with one or more `'` in their launch command:
- 248 titles currently have a single `'` in their launch command (244 Flash and 4 HTML5).
- 294 currently have two or more `'` in their launch command (250 Shockwave and 44 Flash).
- All of these have an even number of `'` (there are no three, five, seven, etc. occurrences.)
Roughly speaking, the Shockwave titles use single quotes that should not be escaped, while Flash and HTML5 titles use apostrophes in URLs that should be escaped. This PR would not fix the 44 Flash titles …

fix: Escape odd numbers of single quotes in launch commands on Linux

---

src/back/game/GameManager.ts

I'm not sure if this is the cleanest place to add the relation filter, or if it should go in the client (which doesn't itself give any filters, so I'm not sure why this accepts a filter).

Include parentGame in addApp searches. Required for AutoMount extension.

---

src/back/Execs.ts
src/back/GameLauncher.ts
src/shared/interfaces.ts

Add support for applicationpath configuration with execs.json for
non-native Linux platforms. If an override path is not found in
execs.json under the key "wine", keep the old default behavior of
using the unconfigurable WINE launch command.
Previous behavior: if "native" was not checked, the system's WINE
would be used to launch the game. This is not sufficiently configurable,
and the long-term plan will use a portable docker environment, launched
from shell scripts.

feat: add ExecMapping support for non-native Linux platforms.

---

src/back/SocketServer.ts

Hyper-V reserves random port ranges, resulting in an EACCES when
we try to listen on a port in that range.

fix: Continue trying ports on EACCES.

---

src/back/index.ts
src/main/Util.ts

This PR fixes four issues that affected MacOS builds.
1. `state.mainFolderPath` (and hence `configFolder`, too) was being set to `DIR/Flashpoint.app/Contents/MacOS`, rather than `DIR`. (#296)
2. The launcher.log was being placed in `DIR/Flashpoint.app/Contents/MacOS`, rather than `DIR`.
3. `state.config.flashpointPath` was interpreted as relative to the current working directory, which is set to `/` by Finder. This was fixed by interpreting a relative `flashpointPath` as relative to the `configFolder`, not relative to the current working directory.
4. The path for the lang jsons was defaulting to `DIR/Flashpoint.app/Contents/MacOS/lang`, instead of `DIR/Flashpoint.app/Contents/lang`.
All of the fixes only take effect when on Mac, so they shouldn't break any other platforms.

fix: mac support

---

src/back/GameLauncher.ts
src/back/ManagedChildProcess.ts

Previously, `wine` wasn't on PATH, because macOS applications are launched with a very odd/minimal PATH.
This *kinda* fixes that - it reads /etc/paths into PATH before launching any games. It's a bit of a hack, but it works. Note that this change will only take effect when the launcher is running on macOS.
This also adds an extra proxy environment variable: the `http_proxy`/`HTTP_PROXY` capitalization convention is a bit unclear (i.e. will likely change depending on the program), so I wanted to cover all the bases.
The eslint check will fail on this. That is because I chose not to fix the missing semicolon in DeveloperPage.tsx, as doing so would cause conflicts with other PRs.

Make macOS able to launch brew-installed (mostly wine'd but php/qemu too) executables.

---

src/back/util/SevenZip.ts

`path.join` will resolve the `..` properly, resulting in the correct path.

fix: use the right path for 7za on Mac.

---

src/back/ManagedChildProcess.ts

Should fix argument escaping issues on Mac.

Get rid of confusing and annoying exec()

---

src/renderer/components/pages/ConfigPage.tsx
src/shared/preferences/util.ts
src/shared/utils/throttle.ts
tests/unit/back/throttle.test.ts

This resolves #280.
Previously: the preference-changed event for logoSet (and hence the requests for the new logos, so that they can be displayed below the dropdown) was emitted without waiting for the `UPDATE_PREFERENCES` signal was sent to the backend. This was caused by a combination of throttling and using `send` instead of `request`. It resulted in a mixture of the previous and correct logo sets - some logo requests were processed by the backend pre-change, some post-change. The "new" images, once requested, were cached by the frontend until the *next* logoSet change.
Now: for logoSet only, we await the completion of the backend request before emitting the preference-changed event.

Fix logoset caching.

---

src/back/GameLauncher.ts

Remove the need for scripts to figure out the fp path themselves.
Previously, scripts had to locate themselves, resulting in a lot of
duplicate code between scripts. Look at the fpdocker scripts, for example.

feat: pass fp path to launched games through env

---

src/back/index.ts

I mentioned this yesterday in #launcher-chat. This prevents the launcher from absolute-ifing the path on each save.

Don't make fp path absolute, just chdir.

---

lang/en.json
src/main/Main.ts
src/renderer/components/pages/ConfigPage.tsx
src/shared/interfaces.ts
src/shared/lang.ts
src/shared/preferences/util.ts
tests/unit/back/configuration.test.ts
typings/flashpoint-launcher.d.ts

Prevents the launcher from forcefully overwriting an existing registration for the "flashpoint://" protocol if the user wants to use another application for that.
The default value `true` keeps existing behavior. Setting the value to `false` not only prevents the launcher from setting itself as the protocol handler, but will remove a prior registration of itself if present.
The non-English strings are all via Google Translate, which I figured was better than nothing.

feat: Make protocol registration a configurable user preference

---

src/back/responses.ts

feat: Strip username from uploaded logs

---

src/back/extensions/util.ts
src/shared/Util.ts

Closes #413
I have a branch where I experimented with introducing ExtendedAppConfigData, which extends AppConfigData to add the property `fullFlashpointPath`. The type replaces AppConfigData nearly everywhere except for the extensions API (to prevent breaking) and when serializing the config back to JSON so that the value isn't written to disk (i.e. transient).
I did this since the absolute path is needed in a number of points throughout the project where it's currently cobbled together in different ways (e.g. IMainWindowExternal), but it still felt like a pretty heavy handed solution for a problem that ultimately can be solved with these two lines. Such an approach might be better long term however.

Resolve absolute Flashpoint path for services/extensions

---

src/back/GameLauncher.ts

On Mac & Linux systems, check if the `FPSoftware/Wine/bin` directory exists relative to fpPath, which shall contain all binaries needed for Wine to function. If it does, add it to the PATH, so Wine launches without the user having to modify it themselves. The PATH will not be modified if the directory doesn't exist, or if the launcher is running on Windows (obviously).

Add Wine to PATH if it's bundled in FPSoftware

---

src/back/responses.ts

The function `findAllPlatforms()` in FPA returns an array of objects, not a dictionary. So `platforms` is not a property of `jsonFile.platforms` which lead to database not being exported.

fix: Correct platforms property in exported database response

---

lang/en.json
src/back/extensions/ApiImplementation.ts
src/back/index.ts
src/back/responses.ts
src/back/types.ts
src/renderer/components/app.tsx
src/renderer/components/pages/ConfigPage.tsx
src/renderer/fpfss.ts
src/shared/back/types.ts
src/shared/lang.ts
typings/flashpoint-launcher.d.ts

This PR introduces the `getAccessToken()` method in a new flashpoint.fpfss namespace, allowing extensions to get access token for the logged in user with FPFSS.
The way it works is that the frontend will still handle the calls to FPFSS and the backend acts like a proxy between the extension and the frontend ~~using a new state `pendingFpfssActions` to keep track of calls between frontend and backend.~~
So even if the user is logged out and the extensions call `getAccessToken()` the main render process will trigger a login to FPFSS by opening the web browser.
**NOTE** there is no warning here, the web browser will open immediately asking for user permission
EDIT 1:
Consent mechanism implemented as discussed. Only the first time the extensions request access to FPFSS the user will be …

Extend fpfss access token into extensions

---

src/back/extensions/ExtensionService.ts
src/back/responses.ts

The backend now reloads all extensions when receiving message from frontend that a reload has happened by hotkey (ctrl+shift+r).
This closes #441

Reload extension when hotkey for window reload is pressed

---

extensions/core-ruffle/src/middleware/standalone.ts

Automatically give the standalone Ruffle binary permission to execute on non-Windows OSes. This allows Mac & Linux users to run Ruffle without having to manually give it execute perms beforehand.

fix: Make Ruffle Executable If Not on Windows
