- src/renderer/LaunchboxData.tsx
- src/renderer/app.tsx
- src/renderer/components/BrowseSidebar.tsx
- src/renderer/components/BrowseSidebarAddApp.tsx
- src/renderer/components/PlaylistItem.tsx
- src/renderer/components/pages/BrowsePage.tsx
- src/renderer/game/GameManager.ts
- src/renderer/game/GameManagerPlatform.ts
- src/renderer/interfaces.ts
- src/renderer/playlist/GamePlaylist.ts
- src/renderer/uuid.ts
- src/shared/game/AdditionalApplicationInfo.ts
- src/shared/game/GameCollection.ts
- src/shared/game/GameParser.ts
- static/renderer/styles/styles.css
Make the "Save Changes" button in the sidebar save the changes to the platform XMLs.
The "create new additional application" button in the sidebar now creates one.
Each additional application in the sidebar now has a "delete" button shaped as a trashcan (shown only if editing is not disabled).
> Save platform xml

- src/main/preferences/AppPreferencesFile.ts
- src/renderer/app.tsx
- src/renderer/components/BrowseSidebar.tsx
- src/renderer/components/BrowseSidebarAddApp.tsx
- src/renderer/components/EditableTextElement.tsx
- src/renderer/components/Header.tsx
- src/renderer/components/LeftBrowseSidebar.tsx
- src/renderer/components/PlaylistItem.tsx
- src/renderer/components/pages/BrowsePage.tsx
- src/renderer/components/pages/PlaylistPage.tsx
- src/renderer/playlist/GamePlaylist.ts
- src/shared/game/GameFilter.ts
- src/shared/preferences/IAppPreferencesData.ts
- static/renderer/styles/styles.css
Added a sidebar on the left side of BrowsePage. It contains all playlists and a button that creates a new one when clicked. It replaces the old PlaylistPage (which is still in here, its just empty).
> Add left sidebar

- src/main/Main.ts
- src/main/background/BackgroundServices.ts
- src/main/background/BackgroundServicesFile.ts
- src/main/preferences/AppPreferencesFile.ts
- src/main/preferences/AppPreferencesMain.ts
- src/renderer/playlist/GamePlaylist.ts
- src/renderer/playlist/GamePlaylistManager.ts
- src/shared/config/AppConfigFile.ts
- src/shared/preferences/IAppPreferencesData.ts
- src/shared/preferences/util.ts
- src/shared/utils/ObjectParser.ts
Add a new set of classes, functions and interfaces that can be used to "parse" objects (that have most likely been loaded from a json file). It provides an easy way to track errors that occurs while parsing, without aborting the parsing process.
> Rework json parsing

- src/renderer/components/GameGrid.tsx
- src/renderer/components/GameImageSplit.tsx
- src/renderer/components/GameList.tsx
- src/renderer/components/RandomGames.tsx
- src/renderer/components/RightBrowseSidebar.tsx
- src/renderer/components/pages/DeveloperPage.tsx
- src/renderer/image/GameImageCollection.ts
- src/renderer/image/ImageFolderCache.ts
- src/renderer/image/util.ts
- static/window/styles/styles.css
Adds a way to add/remove images (screenshots and thumbnails) from games.
Adds a way to open the folder of a games thumbnail/screenshot with that file selected.
> Improve game image

- src/renderer/GameLauncher.ts
- src/renderer/components/pages/ConfigPage.tsx
- src/shared/Util.ts
- src/shared/preferences/IAppPreferencesData.ts
- src/shared/preferences/util.ts
A new preference ("Use Wine") has been added. While it is enabled all
games will be launched using wine.
The hard-coded "replacing" of the application path for flash games on
Linux has been removed.
Add a new "options" parameter for the function stringifyArray, this is
used by GameLauncher to make its process related log messages "cleaner".
There's also some minor cleanup and stuff sprinkled in here.
> feat: add "use wine" preference and basic wine support

- src/renderer/GameLauncher.ts
patches the startUnity and startJava paths
> GameLauncher linux patch

- package.json
- src/renderer/GameLauncher.ts
- src/renderer/app.tsx
- src/renderer/components/pages/BrowsePage.tsx
- src/renderer/components/pages/ConfigPage.tsx
PHP is checked on launch and issues an error if not found.
Wine is checked on launch if useWine is set to true and issues an error if not found.
Wine is checked when useWine is toggled to true and issues an error if not found.
All cases leave a log entry.
>  Wine and PHP missing prompts for Linux 

- .github/workflows/latest.yml
Automatically builds and releases to the 'latest' tag whenever a push is made. Will not release if any platforms fail to build.
Need to register with https://github.com/features/actions
> feat: Github CI build and release latest

- src/renderer/app.tsx
- src/renderer/components/SplashScreen.tsx
- src/renderer/components/pages/HomePage.tsx
- static/window/styles/core.css
- static/window/styles/fancy.css
Waits for the 4 loading flags - games, upgrades, credits and playlists to be true before allowing the rest of the app to load.
> feat: Splash Screen

- src/shared/game/GameFilter.ts
Group 4 now captures special characters
E.G -s@nic now does an inverse search for s@nic.
> fix: Search Regex

- package.json
Fixes an issue related to unmaximize window size being incorrect. Appears to play nicely with everything else.
https://github.com/electron/electron/issues/19930
> feat: Updated Electron - 6.0.0 -> 6.1.5

- src/renderer/components/CurateBox.tsx
- src/shared/curate/metaToMeta.ts
- src/shared/curate/parse.ts
- src/shared/curate/types.ts
> Fix for curation notes missing

- src/back/GameLauncher.ts
- src/renderer/components/pages/ConfigPage.tsx
These fixes have been taken from Colin's setup branch.
> fix basic linux support

- src/back/game/TagManager.ts
- src/back/importGame.ts
- src/back/responses.ts
- src/renderer/components/CurateBox.tsx
- src/renderer/components/RightBrowseSidebar.tsx
- src/renderer/components/RightTagsSidebar.tsx
- src/renderer/components/pages/CuratePage.tsx
- src/renderer/components/pages/TagCategoriesPage.tsx
- src/renderer/containers/ConnectedCuratePage.ts
- src/renderer/context/CurationContext.ts
- src/renderer/curate/util.ts
- src/shared/Util.ts
- src/shared/back/types.ts
- src/shared/curate/metaToMeta.ts
- src/shared/curate/parse.ts
- src/shared/curate/types.ts
- src/shared/curate/util.ts
fix: Can't click New Category button
> feat: Curation Tag Improvements

- lang/en.json
- src/back/index.ts
- src/back/types.ts
- src/back/util/misc.ts
- src/main/index.ts
- src/renderer/components/pages/ConfigPage.tsx
- src/shared/config/interfaces.ts
- src/shared/config/util.ts
- src/shared/lang.ts
- src/shared/preferences/interfaces.ts
- src/shared/preferences/util.ts
Download missing game thumbnails and screenshots on demand from a remote server.
> Images on demand

- src/back/ServicesFile.ts
- src/back/index.ts
- src/renderer/components/ServiceBox.tsx
- src/shared/Log/LogCommon.ts
- src/shared/Util.ts
feat: Flashpoint Path substitutable in Service File opts
> fix: Temp fix for entries array gap crash

- lang/en.json
- src/back/responses.ts
- src/renderer/components/pages/LogsPage.tsx
- src/shared/back/types.ts
- src/shared/config/interfaces.ts
- src/shared/config/util.ts
- src/shared/lang.ts
See https://logs.unstable.life/
> Log Server Uploads

- src/main/Main.ts
* Allow only one instance of the "main" mode (multiple instances in the
"flash" mode is allowed)
* Fix bug where "state.window" in main was never assigned a window
* Add a note about why "app.allowRendererProcessReuse" is set to true
> feat: only allow one instance (flash excluded)

- src/renderer/components/CurateBox.tsx
- src/renderer/components/pages/HomePage.tsx
- static/window/styles/core.css
- static/window/styles/fancy.css
Bringing formatting improvements from the Metal themes to the fallback CSS. Changes affect mainly margin/padding values, with any major visual tweaks going to the center boxes throughout the launcher. Will have compatibility issues of varying levels with older themes (they will need to be updated).
> Fallback CSS refresh

- src/renderer/components/CurateBox.tsx
- src/renderer/components/TagListHeader.tsx
- src/renderer/components/TagListItem.tsx
- static/window/styles/core.css
- static/window/styles/fancy.css
- Tag/Category pages are more visually consistent to Game/Animation pages
- Universal floating box style reverted back to individual styles
- Padding fixes on Curation page
> More CSS changes (done right this time)

- package.json
- src/back/index.ts
- src/back/responses.ts
- src/back/types.ts
- src/main/MainWindowPreload.ts
- src/renderer/app.tsx
- src/shared/back/types.ts
- src/shared/interfaces.ts
Adding a custom version to show in the title bar so packaged versions of the launcher can more easily identify themselves to the content which it comes with.
> Custom Version - Hotfix/9.0.1

- .github/workflows/latest.yml
- CHANGELOG.md
- gulpfile.js
- package.json
- src/back/game/GameManager.ts
- src/back/importGame.ts
- src/back/index.ts
- src/back/responses.ts
- src/renderer/components/CurateBox.tsx
- src/renderer/components/GameOrder.tsx
- src/renderer/components/Header.tsx
- src/renderer/components/RightBrowseSidebar.tsx
- src/renderer/components/TagInputField.tsx
- src/renderer/components/pages/BrowsePage.tsx
- src/renderer/components/pages/CuratePage.tsx
- src/renderer/components/pages/LogsPage.tsx
- src/renderer/components/pages/TagCategoriesPage.tsx
- src/renderer/components/pages/TagsPage.tsx
- src/renderer/containers/HeaderContainer.tsx
- src/renderer/context/CurationContext.ts
- src/renderer/curate/importCuration.ts
- src/renderer/hooks/useThrottle.ts
- src/shared/back/types.ts
- src/shared/curate/parse.ts
- src/shared/curate/types.ts
- src/shared/curate/util.ts
- src/shared/order/util.ts
- static/window/styles/core.css
- static/window/styles/fancy.css
Reminder - Do not pull hotfixes on Github
> Hotfix 9.0.3

- lang/en.json
- package.json
- src/back/GameLauncher.ts
- src/back/responses.ts
- src/renderer/components/pages/ConfigPage.tsx
- src/shared/lang.ts
- src/shared/preferences/interfaces.ts
- src/shared/preferences/util.ts
- static/window/styles/core.css
- static/window/styles/fancy.css
- typings/flashpoint.d.ts
App Path Overrides added to the Config page.
Overrides the left app path with the right app path whenever launching a game / add app.
Can make as many as you want.
> feat: Application Path Overrides

- src/renderer/components/CheckBox.tsx
- static/window/styles/core.css
- static/window/styles/fancy.css
Still uses Checkbox component name.
> Feature: Reworked Checkboxes into Sliders

- static/window/styles/core.css
easy center the logos. 
fixes #198
> fix #198 logo set images not centering correctly

- src/renderer/components/RightBrowseSidebar.tsx
> Hide notes & og-description if empty

- src/renderer/components/GameList.tsx
- src/renderer/components/GameListHeader.tsx
- src/renderer/components/pages/BrowsePage.tsx
- static/window/styles/core.css
> sort by a field in a list by clicking on the header

- src/back/Execs.ts
- src/back/GameLauncher.ts
- src/shared/interfaces.ts
> feat: make wine-execmapping configurable on Mac too

- src/renderer/curate/importCuration.ts
#309 introduced a bug, this fixes it.
> Fix getRootPath()

- src/shared/Util.ts
- src/shared/preferences/PreferencesFile.ts
Also make onError actually get called in readOrCreateFile().
> refactor: change some confusing Promise() functions into clearer async's.

- src/back/util/misc.ts
- src/renderer/components/GameItemContainer.tsx
- src/renderer/components/TagItemContainer.tsx
- src/shared/back/SocketClient.ts
- src/shared/socket/SocketAPI.ts
- src/shared/socket/SocketServer.ts
- src/shared/socket/types.ts
- tsconfig.json
Reverse the change to tsconfig.json in 093c684, and fix the compiler errors that result.
> fix: turn strictNullChecks on.

- src/back/GameLauncher.ts
This removes support for the :flash: ApplicationPath from GameLauncher.
> fix: remove flash browser mode

- package-lock.json
- src/shared/Util.ts
- src/shared/preferences/PreferencesFile.ts
Also add some size checks and error messages.
The launcher gets five tries to successfully write the preferences, after that we bail out.
> fix: use temp-rename writing for preference saving

- src/shared/socket/SocketServer.ts
Pretty much what it says. Doesn't change external typings or anything, it just makes the internal code make more sense.
> Remove confusing broadcast promise.

- src/back/responses.ts
Was being called for every game launch.
> Fix: Removed five second game startup delay

- static/window/styles/core.css
> Remove tag page flickering

- src/renderer/components/CurateBox.tsx
This PR adds dependencies to the callbacks for tags and platform.
Fixes #442
> Fix curatation prop state
